name: Job Scraper

on:
  schedule:
    # Runs every 30 minutes from 9 AM to 11:59 PM EST (14:00 to 23:00 UTC)
    - cron: "*/30 14-23 * * *"
    # Runs every 30 minutes from 12 AM to 2:59 AM EST (00:00 to 03:00 UTC)
    - cron: "*/30 0-3 * * *"
  workflow_dispatch: # Allows manual runs

jobs:
  scrape-jobs:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout repository
        uses: actions/checkout@v3

      - name: Set up Python 3.11
        uses: actions/setup-python@v4
        with:
          python-version: "3.11"

      - name: Install dependencies
        run: |
          python -m pip install --upgrade pip
          pip install -r requirements.txt

      - name: Run job scraper
        env:
          USERNAME: ${{ secrets.USERNAME }}
          PASSWORD: ${{ secrets.PASSWORD }}
          SUPABASE_URL: ${{ secrets.SUPABASE_URL }}
          SUPABASE_KEY: ${{ secrets.SUPABASE_KEY }}
          EMAIL_ADDRESS: ${{ secrets.EMAIL_ADDRESS }}
          EMAIL_PASSWORD: ${{ secrets.EMAIL_PASSWORD }}
          RECIPIENT_EMAIL: ${{ secrets.RECIPIENT_EMAIL }}
        run: python script.py

